### ISSUE TITLE
Question about hidding the URL bar

### ISSUE THREAD

**Issue by danielsawan** [google/cordova-plugin-browsertab#12]
Hi :)

I was wondering if it is possible to send options to the browser tab like in InAppBrowser for exemple to hide the URL bar etc.

Thanks.

**Comment by WilliamDenniss** [comment]
No, it's not possible, as in-app browser tabs (Chrome Custom Tab on Android, and SFSafariViewController on iOS) don't support such an option.

**Comment by danielsawan** [comment]
Ok that's what i was thinking. Thanks for the reply !
