### ISSUE TITLE
Release changes to npm

### ISSUE THREAD

**Issue by bayssmekanique** [google/cordova-plugin-browsertab#14]
There have been several minor code improvements in the last few months but no npm release and the repo is structured in a way that prevents it from being pulled directly into Cordova projects.

Can we get a release to npm with the recent changes, please?

**Comment by aggarwalankush** [comment]
I'm also waiting for this but I found a workaround till then. You can download the repository and run following command to add plugin.

`cordova plugin add /path/to/my/plugin/my.plugin.folder.here/`

for example,
`cordova plugin add /Users/Ankush/Downloads/cordova-plugin-browsertab-master/plugin`

reference - http://stackoverflow.com/questions/30345035/how-to-add-a-local-cordova-plugin-with-ionic

**Comment by iainmcgin** [comment]
I've pushed 0.2.0 - sorry for the huge delay, this project is pretty low on my current set of priorities.
