### ISSUE TITLE
Cordova 10 - Suport

### ISSUE THREAD

**Issue by antonioEDER** [google/cordova-plugin-browsertab#42]
Installing "cordova-plugin-browsertab" for android

Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 10.1.1, failed version requirement: 
      <6.3.0
      
Skipping 'cordova-plugin-compat' for android

cordova run android

* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

**Comment by antonioEDER** [comment]
A Adobe descontinuará o PhoneGap, o PhoneGap Build e o Apache Cordova em 1º de outubro de 2020. Recomendamos mover seus dados antes dessa data.

https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c

**Comment by rachmadideni** [comment]
@antonioEDER i have the same problem when installing plugin. how the provided link (https://github.com/google/cordova-plugin-browsertab/issues/42#issuecomment-995831782) related with your current issue ?  is the issue solved now ?
